### ISSUE TITLE
Add .master to file extensions

### ISSUE THREAD

**Issue by kyleschaeffer** [Trickierstinky/language-asp#6]
Thanks for this extension, it's great. Any chance you can add .master as a file type extension? I use Atom to build ASP.NET master pages, and it would be convenient if it automatically recognized these files.

**Comment by toothbrush7777777** [comment]
@kyleschaeffer This package explicitly states it is for **Classic** ASP (and therefore not useful for ASP.NET).

**Comment by Trickierstinky** [comment]
Agreed, will close this issue for now.
